# Generated by Django 4.1.7 on 2023-03-22 06:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(null=True, upload_to='programs/')),
                ('stream_status', models.CharField(choices=[('WAITING', '대기중'), ('STREAMING', '방송중'), ('ENDED', '종료')], max_length=20)),
                ('stream_scheduled_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
