# Generated by Django 4.2 on 2023-04-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='stream_status',
            field=models.CharField(choices=[('LI', 'Live'), ('UP', 'Upcoming'), ('FI', 'Finished'), ('CA', 'Cancelled'), ('PA', 'Paused')], default='UP', max_length=2),
        ),
    ]
