# Generated by Django 4.1.7 on 2023-04-10 04:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lives', '0002_alter_program_description_alter_program_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='program',
            name='stream_status',
            field=models.CharField(choices=[('live', 'Live'), ('upcoming', 'Upcoming'), ('finished', 'Finished')], default='upcoming', max_length=100),
        ),
    ]
