# Generated by Django 4.1.7 on 2023-04-10 04:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lives', '0003_alter_program_id_alter_program_stream_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
